### ISSUE TITLE
Document `lb_web` network config / add port mapping to web service

### ISSUE THREAD

**Issue by chiefy** [libresh/compose-nextcloud#8]
The current docs don't really mention what `lb_web` should be? I assume bridged networking. Also, there's no port mapping for nginx in the current `docker-compose.yml`?

```
...
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    networks:
    - back
    - lb_web
...
```
